service:
  name: ignitecertificate

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-eats-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  generateCertificate:
    handler: src/functions/generateCertificate.handle
    events:
      - http:
          path: /generateCertificate
          method: POST
          cors: true
  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events:
      - http:
          path: /verifyCertificate/{id}
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_certificates
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttibuteName: id
            AttributeType: S
        KeySchema:
          - AttibuteName: id
            KeyType: HASH
